app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from article.urls import router as blog_router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('article/',  include('article.urls')),
    path('',  include('stweb.urls')),
    path('martor/', include('martor.urls')),
    path('api/', include(blog_router.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

martor/urls.py
import django
from .views import (markdownfy_view,
                    markdown_imgur_uploader,
                    markdown_search_user)


if django.VERSION >= (2, 0):
    from django.urls import path
    urlpatterns = [
        path('markdownify/', markdownfy_view, name='martor_markdownfy'),
        path('uploader/', markdown_imgur_uploader, name='imgur_uploader'),
        path('search-user/', markdown_search_user, name='search_user_json'),
    ]
else:
    from django.conf.urls import url
    urlpatterns = [
        url(r'^markdownify/$', markdownfy_view, name='martor_markdownfy'),
        url(r'^uploader/$', markdown_imgur_uploader, name='imgur_uploader'),
        url(r'^search-user/$', markdown_search_user, name='search_user_json'),
    ]

stweb/urls.py
from django.urls import path

from . import views

app_name = 'stweb'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('category_detail/<int:pk>', views.category_detail, name='category_detail'),
    path('tag_detail/<int:pk>', views.tag_detail, name='tag_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

stweb/models.py
from django.db import models

# Create your models here.

stweb/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.conf import settings

class ContactForm(forms.Form):
    name = forms.CharField(label='名前') # 名前
    message = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea) #問い合わせ内容

    # メール送信処理
    def send_email(self):
        # send email using the self.cleaned_data dictionary
        subject = self.cleaned_data['name']
        message = self.cleaned_data['message']
        from_email = settings.EMAIL_HOST_USER
        to = [settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to)

stweb/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, FormView
from article.models import Category, Article, Tag
from user.models import User
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from pure_pagination.mixins import PaginationMixin

from .forms import ContactForm


class IndexView(PaginationMixin, ListView):
    model = Article
    template_name = 'stweb/index.html'
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        contact_list = Article.objects.filter(publick=1).order_by('-created_at')
        paginator = Paginator(contact_list, 9)
        try:
            page = int(self.request.GET.get('page'))
        except:
            page = 1

        try:
            contact_list = paginator.page(page)
        except(EmptyPage, InvalidPage):
            contact_list = paginator.page(1)

        context['object_list'] = contact_list
        context['articles'] = Article.objects.filter(publick=1).order_by('-created_at')[:3]
        context['count'] = Article.objects.filter(publick=1).count()
        context['more_context'] = Category.objects.all()
        context['more_tags'] = Tag.objects.all()

        return context

index = IndexView.as_view()


class Detail(DetailView):
    model = Article
    template_name = 'stweb/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['more_context'] = Category.objects.all()
        context['more_tags'] = Tag.objects.all()
        return context

detail = Detail.as_view()

class CategoryDetail(DetailView):
    model = Category
    template_name = 'stweb/category_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article_list'] = Article.objects.filter(category_id=self.object.id, publick=1).order_by('id')
        context['count'] = Article.objects.filter(category_id=self.object.id).filter(publick=1).count()
        context['more_context'] = Category.objects.all()
        context['more_tags'] = Tag.objects.all()
        return context

category_detail = CategoryDetail.as_view()


class TagDetail(DetailView):
    model = Tag
    template_name = 'stweb/tag_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article_list'] = Tag.objects.get(id=self.object.id)
        context['more_context'] = Category.objects.all()
        context['more_tags'] = Tag.objects.all()
        return context

tag_detail = TagDetail.as_view()

class About(TemplateView):
    template_name = "stweb/about.html"

about = About.as_view()


class ContactView(FormView):
    template_name = 'stweb/contact.html'
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_email()
        return super(ContactView, self).form_valid(form)

contact = ContactView.as_view()

templates/stweb/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>stwebについて</h2>
<p>stwebは2017年末からプログラミングの勉強を始め、翌年4月より現場に入り仕事をしています。</p>
<p>今の現場ではWEB制作を担当しているため、HTML、CSS、JSを使用。<br/>
個人ではPython、Ruby、PHP（予定）を使ってプログラミングを嗜んだり。</p>
<p>stweblogで日々の日記や勉強したことを自分の備忘録として、皆さんにもわかりやすく伝えられたらいいなーと思っています。</p>
<p>このブログでどなたか1人でも多くの助けになればstwebは舞い踊ります！</p>
<p>少しずつ機能を追加していくつもりなので、もしこういう機能があればどう？という貴重なご意見をいただけるようでしたら、contactページからメッセージを頂戴できますとほくそ笑んで喜びます。</p>
{% endblock %}

templates/stweb/category_detail.html
{% extends "base_detail.html" %}
{% load static %}

{% block pankuzu %}
<div class="container">
<div class="article-detail-pan">
<a href="/">Home</a> > <span>{{ object.name }}</span>
</div>
</div>
{% endblock %}

{% block content %}
<p class="article-count"><span class="font-title">投稿記事:{{ count }}件</span></p>
<p class="text-center index_title">＜<span class="font-bold">{{ object.name }}</span>＞の記事一覧</p>
<div class="row">
  {% for field in article_list %}
  <div class="col-lg-4 col-sm-6">
  <div class="article">
    <div class="article-header">
      <span class="font-small">投稿日:{{field.created_at|date:"Y年n月j日"}}　
        <br />カテゴリ：<a href="{% url 'stweb:category_detail' pk=field.category_id %}">{{ field.category_find }}</a>
        　<br />タグ：{% for tags in field.tag_find %}
                <a href="{% url 'stweb:tag_detail' pk=tags.id %}">{{ tags.name }}</a>
              {% endfor %}
    </span>
    </div>
    <a href="{% url 'stweb:detail' pk=field.id %}" class="article-text">
    <h2 class="t-bg-darkgray-right">{{ field.title }}</h2>
    {% if field.thumnail %}
    <div class="article-thumnail">
      <img class="img-responsive" src="/media/{{ field.thumnail }}">
    </div>
    {% else %}
    {% endif %}
    <div class="t-bg-darkgray-right article-discript">
      <span class="">{{ field.discript }}</span>
    </div>
    <div class="article-see">>> Read more</div>
    </a>
</div>
</div>
{% endfor %}
</div>
{% endblock %}

templates/stweb/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="l-contact contact">
<h4>stwebにメール</h4>
<p>ご意見やお問い合わせはこちらから</p>
<form action="" method="post" class="form">
  {% csrf_token %}
  {% for field in form %}
      <ul>
        <li>{{ field.label }}</li>
        <li>{{ field }}</li>
      </ul>
      {% endfor %}
<input type="submit" value="管理者にメール" class="contact-btn">
</form>
</div>
{% endblock %}

{% block extra_script %}
<script>
var simplemde = new SimpleMDE({
  element: document.getElementById("text-area"),
  autofocus: true,
  forceSync: true,
  placeholder: "本文",
});
</script>
{% endblock %}

templates/stweb/detail.html
{% extends "base.html" %}
{% load static %}
{% load martortags %}

{% block pankuzu %}
<div class="container">
<div class="article-detail-pan">
<a href="/">Home</a> > <a href="{% url 'stweb:category_detail' pk=object.category_id %}">{{ object.category_find }}</a> > <span>{{ object.title }}</span>
</div>
</div>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-9">
    <div class="article-detail-wrap">
      <div class="article-deatil-link">
        {% if object.updated_at == object.created_at %}
        <span class="font-small">投稿日:{{object.created_at|date:"Y年n月j日"}}</span>
        {% else %}
        <span class="font-small">投稿日:{{object.created_at|date:"Y年n月j日"}}</span>
        　<span class="font-small">追記日：{{ object.updated_at }}</span>
        {% endif %}
        　<br /><span class="font-small">カテゴリ：<a href="{% url 'stweb:category_detail' pk=object.category_id %}" class="link-view">{{ object.category_find }}</a>　タグ：
        {% for tags in object.tag_find %}
          <a href="{% url 'stweb:tag_detail' pk=tags.id %}" class="link-view">{{ tags.name }}</a>
        {% endfor %}
      </span>
      </div>
        <div class="article-detail-title">{{ object.title }}</div>
        <div class="article-detail-discript">{{ object.discript }}</div>
        {% if object.thumnail %}
        <img class="img-responsive" src="/media/{{ object.thumnail }}">
        {% else %}
        {% endif %}
        <div id="a"></div>
        <div id="mk-text" class="article-detail-text">{{ object.text|safe_markdown }}</div>
    </div>
  </div>
  <div class="col-sm-3 text-center">
  {% include 'category_list_publick.html' %}
  {% include 'tag_list_publick.html' %}
</div>
</div>
{% endblock %}
{% block extra_script %}
<script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
<script>
    $('pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
    $('.ui.dropdown').dropdown();
  </script>
{% endblock %}

templates/stweb/index.html
{% extends "base_index.html" %}

{% block pankuzu %}
<div class="container">
<div class="article-detail-pan">
<span>Home</span>
</div>
</div>
{% endblock %}

{% load static %}
{% block content %}
<p class="article-count"><span class="font-title">投稿記事:{{ count }}件</span></p>
<div class="row">
  {% for field in object_list %}
  <div class="col-lg-4 col-sm-6">
    <div class="article">
      <div class="article-header">
        <span class="font-small">{{field.created_at|date:"Y年n月j日"}}<br />
          カテゴリ：<a href="{% url 'stweb:category_detail' pk=field.category_id %}">{{ field.category_find }}</a>
          　<br />タグ：{% for tags in field.tag_find %}
          <a href="{% url 'stweb:tag_detail' pk=tags.id %}">{{ tags.name }}</a>
          {% endfor %}
          <!-- <span class="text-right">ユーザー：{{ field.user_find }}</span> -->
        </span>
      </div>
      <a href="{% url 'stweb:detail' pk=field.id %}" class="article-text">
        <h2 class="t-bg-darkgray-right">{{ field.title }}</h2>
        {% if field.thumnail %}
        <div class="article-thumnail">
          <img class="img-responsive" src="/media/{{ field.thumnail }}">
        </div>
        {% else %}
        {% endif %}
        <div class="article-mr">
          <div class="t-bg-darkgray-right article-discript">
            <span class="">{{ field.discript }}</span>
          </div>
          <div class="article-see">>> Read more</div>
        </div>
      </a>
    </div>
  </div>
  {% endfor %}
</div>
  {% include 'pagenation.html' %}

{% endblock %}

templates/stweb/tag_detail.html
{% extends "base_detail.html" %}
{% load static %}

{% block pankuzu %}
<div class="container">
  <div class="article-detail-pan">
    <a href="/">Home</a> > <span>{{ object.name }}</span>
  </div>
</div>
{% endblock %}

{% block content %}
<p class="article-count"><span class="font-title">投稿記事:{{ object.tag_count_publick }}件</span></p>
<p class="text-center index_title">＜<span class="font-bold">{{ object }}</span>＞の記事一覧</p>
<div class="row">
  {% for field in article_list.article_find %}
  <div class="col-lg-4 col-sm-6">
    <div class="article">
      <div class="article-header">
        <span class="font-small">投稿日:{{field.created_at|date:"Y年n月j日"}}　
          <br />カテゴリ：<a href="{% url 'stweb:category_detail' pk=field.category_id %}" class="link-view">{{ field.category_find }}</a>
          　<br />タグ：{% for tags in field.tag_find %}
          <a href="{% url 'stweb:tag_detail' pk=tags.id %}" class="link-view">{{ tags.name }}</a>
          {% endfor %}
        </span>
      </div>
      <a href="{% url 'stweb:detail' pk=field.id %}" class="article-text">
        <h2 class="t-bg-darkgray-right">{{ field.title }}</h2>
        {% if field.thumnail %}
        <div class="article-thumnail">
          <img class="img-responsive" src="/media/{{ field.thumnail }}">
        </div>
        {% else %}
        {% endif %}
        <div class="t-bg-darkgray-right article-discript">
          <span class="">{{ field.discript }}</span>
        </div>
        <div class="article-see">>> Read more</div>
      </a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}