app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from article.urls import router as blog_router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('article/',  include('article.urls')),
    path('',  include('stweb.urls')),
    path('martor/', include('martor.urls')),
    path('api/', include(blog_router.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import ArticleViewSet,TagViewSet, CategoryViewSet


app_name = 'article'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('delete/<int:pk>', views.article_delete, name='article_delete'),
    path('category_detail/<int:pk>', views.category_detail, name='category_detail'),
    path('category/post', views.category_post, name='category_post'),
    path('category/delete/<int:pk>', views.category_delete, name='category_delete'),
    path('tag_detail/<int:pk>', views.tag_detail, name='tag_detail'),
    path('tag/post', views.tag_post, name='tag_post'),
    path('tag/delete/<int:pk>', views.tag_delete, name='tag_delete'),
]

router = routers.DefaultRouter()
router.register(r'articles', ArticleViewSet)
router.register(r'tags', TagViewSet)
router.register(r'categpries', CategoryViewSet)

martor/urls.py
import django
from .views import (markdownfy_view,
                    markdown_imgur_uploader,
                    markdown_search_user)


if django.VERSION >= (2, 0):
    from django.urls import path
    urlpatterns = [
        path('markdownify/', markdownfy_view, name='martor_markdownfy'),
        path('uploader/', markdown_imgur_uploader, name='imgur_uploader'),
        path('search-user/', markdown_search_user, name='search_user_json'),
    ]
else:
    from django.conf.urls import url
    urlpatterns = [
        url(r'^markdownify/$', markdownfy_view, name='martor_markdownfy'),
        url(r'^uploader/$', markdown_imgur_uploader, name='imgur_uploader'),
        url(r'^search-user/$', markdown_search_user, name='search_user_json'),
    ]

stweb/urls.py
from django.urls import path

from . import views

app_name = 'stweb'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('category_detail/<int:pk>', views.category_detail, name='category_detail'),
    path('tag_detail/<int:pk>', views.tag_detail, name='tag_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<uuid:uuid>/', views.profile, name='profile'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
<meta charset="utf-8">
<title>stweBlog</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<!-- <link href="{% static 'plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" /> -->
<link href="{% static 'plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'martor/css/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style_new.css' %}">
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?skin=sunburst"></script> -->
{% block stylesheet %}
{% endblock %}
<!--[if lt IE 9]>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
<![endif]-->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-128249886-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-128249886-1');
</script>
</head>
<body class="d-flex flex-column">
    <nav class="navbar navbar-expand-md t-bg-thinbk">
      <div class="nav-img">
        <a href="/">
          <img src="/static/images/logo_edit3.png" height="100px">
          <span class="nav-sitename">stweBlog</span>
        </a>
      </div>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav nav-left font-robot">
          <li><a class="nav-item active nav-link" href="/">Home</a><span class="sr-only">(現位置)</span></li>
          <li><a class="nav-item nav-link" href="{% url 'stweb:about' %}">about</a></li>
          <li><a class="nav-item nav-link" href="{% url 'stweb:contact' %}">Contact</a></li>
        <!-- {% if user.is_authenticated %}
          <li><a class="nav-item nav-link" href="{% url 'user:index' %}">User</a></li>
          <li><a class="nav-item nav-link" href="{% url 'article:index' %}">Article</a></li>
        {% endif %}
        {% if user.is_authenticated %}
          <li class="dropdown nav-item">
             <a class="btn btn-white dropdown-toggle nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{ user.username }}
             </a>
             <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'article:index' %}">記事管理画面</a>
                <a class="dropdown-item" href="{% url 'user:profile' uuid=user.uuid %}">プロフィール変更</a>
                <a class="dropdown-item" href="{% url 'user:logout' %}">ログアウト</a>
            </div>
          </li>
        {% else %}
        {% endif %} -->
        </ul>
      </div>
    </nav>
    {% block pankuzu %}
    {% endblock %}
      <div class="container  t-bg-darkgray box-shadow">
        <div class="row mt20">
          <div class="col-12 col-lg-12">
      {% for message in messages %}
      <ul class="alert alert-primary">
        <li>{{ message }}</li>
      </ul>
      {% endfor %}
    {% block content %}
    {% endblock %}
    </div>
    </div>
  </div>
  <div id="footer" class="parallax-window" data-parallax="scroll" data-image-src="../../static/images/footer_bg2.jpg" style="margin-top:50px;">
  <footer>
    <div class="l-footer">
      <div class="footer-contact">
        <p><a href="{% url 'stweb:contact' %}">お問い合わせはこちらから</a></p>
      </div>
    </div>
    <div class="footer-logo">
      <span class="copyright">@2018 Copyright stweb All Rights Reserved.</span>
      <span class="footer-img">
      <a href="/">
        <img src="/static/images/logo_edit3.png" height="100px">
      </a>
    </span>
  </div>
  </footer>
  </div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ace.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/mode-markdown.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/ext-language_tools.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/theme-github.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/resizable.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/js/emojis.min.js' %}"></script>
<script type="text/javascript" src="{% static 'martor/js/martor.min.js' %}"></script>
<!-- <script src="{% static 'js/marked.js' %}"></script>
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script> -->
<!-- <script>
$(document).ready(function() {
          $("code").wrap("<pre class='prettyprint linenums'></pre>");
      });
</script> -->
{% block extra_script %}
{% endblock %}
</body>
</html>

templates/base_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
<meta charset="utf-8">
<title>stweBlog</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style_new.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?skin=sunburst"></script>
{% block stylesheet %}
{% endblock %}
<!--[if lt IE 9]>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
<![endif]-->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-128249886-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-128249886-1');
</script>
</head>
<body class="d-flex flex-column">
  <nav class="navbar navbar-expand-md t-bg-thinbk">
    <div class="nav-img">
      <a href="/">
        <img src="/static/images/logo_edit3.png" height="100px">
        <span class="nav-sitename">stweBlog</span>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="Navber">
      <ul class="navbar-nav nav-left font-robot">
        <li><a class="nav-item active nav-link" href="/">Home</a><span class="sr-only">(現位置)</span></li>
        <li><a class="nav-item nav-link" href="{% url 'stweb:about' %}">about</a></li>
        <li><a class="nav-item nav-link" href="{% url 'stweb:contact' %}">Contact</a></li>
      <!-- {% if user.is_authenticated %}
        <li><a class="nav-item nav-link" href="{% url 'user:index' %}">User</a></li>
        <li><a class="nav-item nav-link" href="{% url 'article:index' %}">Article</a></li>
      {% endif %}
      {% if user.is_authenticated %}
        <li class="dropdown nav-item">
           <a class="btn btn-white dropdown-toggle nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             {{ user.username }}
           </a>
           <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'article:index' %}">記事管理画面</a>
              <a class="dropdown-item" href="{% url 'user:profile' uuid=user.uuid %}">プロフィール変更</a>
              <a class="dropdown-item" href="{% url 'user:logout' %}">ログアウト</a>
          </div>
        </li>
      {% else %}
      {% endif %} -->
      </ul>
    </div>
  </nav>
  {% block pankuzu %}
  {% endblock %}
      <div class="container t-bg-darkgray box-shadow">
        <div class="row mt20">
          <div class="col-12 col-lg-8">
      {% for message in messages %}
      <ul class="alert alert-primary">
        <li>{{ message }}</li>
      </ul>
      {% endfor %}
    {% block content %}
    {% endblock %}
    </div>
    <div class="col-sm-4 text-center">
      {% include 'category_list_publick.html' %}
      {% include 'tag_list_publick.html' %}
  </div>


    </div>
  </div>
  <div id="footer" class="parallax-window" data-parallax="scroll" data-image-src="../../static/images/footer_bg2.jpg" style="margin-top:50px;">
<footer>
  <div class="l-footer">
    <div class="footer-contact">
      <p><a href="{% url 'stweb:contact' %}">お問い合わせはこちらから</a></p>
    </div>
  </div>
  <div class="footer-logo">
    <span class="copyright">@2018 Copyright stweb All Rights Reserved.</span>
    <span class="footer-img">
    <a href="/">
      <img src="/static/images/logo_edit3.png" height="100px">
    </a>
  </span>
</div>
</footer>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/marked.js' %}"></script>
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
$(document).ready(function() {
          $("code").wrap("<pre class='prettyprint linenums'></pre>");
      });
</script>
{% block extra_script %}
{% endblock %}
</body>
</html>

templates/base_index.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
<meta charset="utf-8">
<title>stweBlog</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style_new.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?skin=sunburst"></script>
{% block stylesheet %}
{% endblock %}
<!--[if lt IE 9]>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
<![endif]-->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-128249886-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-128249886-1');
</script>
</head>
<body class="d-flex flex-column">
  <div id="header" class="l-header parallax-window" data-parallax="scroll" data-image-src="../../static/images/top_bg2.jpg">
<nav class="navbar navbar-expand-md t-bg-thinbk">
  <div class="nav-img">
    <a href="/">
      <img src="/static/images/logo_edit3.png" height="100px">
      <span class="nav-sitename">stweBlog</span>
    </a>
  </div>
  <div class="collapse navbar-collapse" id="Navber">
    <ul class="navbar-nav nav-left font-robot">
      <li><a class="nav-item active nav-link" href="/">Home</a><span class="sr-only">(現位置)</span></li>
      <li><a class="nav-item nav-link" href="{% url 'stweb:about' %}">about</a></li>
      <li><a class="nav-item nav-link" href="{% url 'stweb:contact' %}">Contact</a></li>
    <!-- {% if user.is_authenticated %}
      <li><a class="nav-item nav-link" href="{% url 'user:index' %}">User</a></li>
      <li><a class="nav-item nav-link" href="{% url 'article:index' %}">Article</a></li>
    {% endif %}
    {% if user.is_authenticated %}
      <li class="dropdown nav-item">
         <a class="btn btn-white dropdown-toggle nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           {{ user.username }}
         </a>
         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'article:index' %}">記事管理画面</a>
            <a class="dropdown-item" href="{% url 'user:profile' uuid=user.uuid %}">プロフィール変更</a>
            <a class="dropdown-item" href="{% url 'user:logout' %}">ログアウト</a>
        </div>
      </li>
    {% else %}
    {% endif %} -->
    </ul>
  </div>
</nav>
<div class="l-main">
  <h2 class="l-main-title main-title">
    <span class="main-title-bg" style="text-align: center;">
      <a href="/">stweBlog</a>
      <br>
    <span class="main-subtitle">備忘録をまとめたブログ</span></span>
  </h2>
</div>
</div>
{% block pankuzu %}
{% endblock %}
      <div class="container t-bg-darkgray box-shadow article-pd">
        <div class="row mt20">
          <div class="col-12 col-lg-8">
      {% for message in messages %}
      <ul class="alert alert-primary">
        <li>{{ message }}</li>
      </ul>
      {% endfor %}
    {% block content %}
    {% endblock %}
    </div>
    <div class="col-sm-4 text-center">
      {% include 'category_list_publick.html' %}
      {% include 'tag_list_publick.html' %}
  </div>


    </div>
  </div>
  <div id="footer" class="parallax-window" data-parallax="scroll" data-image-src="../../static/images/footer_bg2.jpg" style="margin-top:50px;">
<footer>
  <div class="l-footer">
    <div class="footer-contact">
      <p><a href="{% url 'stweb:contact' %}">お問い合わせはこちらから</a></p>
    </div>
  </div>
  <div class="footer-logo">
    <span class="copyright">@2018 Copyright stweb All Rights Reserved.</span>
    <span class="footer-img">
    <a href="/">
      <img src="/static/images/logo_edit3.png" height="100px">
    </a>
  </span>
</div>
</footer>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/marked.js' %}"></script>
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<script>
$(document).ready(function() {
          $("code").wrap("<pre class='prettyprint linenums'></pre>");
      });
</script>
{% block extra_script %}
{% endblock %}
</body>
</html>

templates/category_list.html
  <div class="">
    <p class="font-white">カテゴリ一覧</p>
    <div class="categories">
      {% for categories in more_context %}
      <ul>
        <li><a href="{% url 'article:category_detail' pk=categories.id %}" class="font-yellow">{{ categories.name }}：{{ categories.article_count }}件</a></li>
      </ul>
      {% endfor %}
    </div>
  </div>

templates/category_list_publick.html
  <div class="">
    <p class="font-white">カテゴリ一覧</p>
    <div class="categories">
      {% for categories in more_context %}
      <ul>
        <li><a href="{% url 'stweb:category_detail' pk=categories.id %}" class="font-yellow">{{ categories.name }}：{{ categories.article_count_publick }}件</a></li>
      </ul>
      {% endfor %}
    </div>
  </div>

templates/pagenation.html
{% if is_paginated %}
<nav class="pagenation-mt" aria-label="pagenation_base">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="pagenation-list">
              <a class="pagenation-link" href="?{{ page_obj.previous_page_number.querystring }}">前へ</a>
            </li>
        {% endif %}
        {% for link_page in page_obj.pages %}
            {% if link_page %}
                {% if link_page == page_obj.number %}
                    <li class="pagenation-list active">
                      <span class="pagenation-link">{{ link_page }}</span>
                    </li>
                {% else %}
                    <li class="pagenation-list">
                      <a class="pagenation-link" href="?{{ link_page.querystring  }}">{{ link_page }}</a>
                    </li>
                {% endif %}
            {% else %}
                {# 省略された部分の表示内容 #}
                <li class="disabled"><a class="page-link" href="#">...</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="pagenation-list">
              <a class="pagenation-link" href="?{{ page_obj.next_page_number.querystring }}">次へ</a>
            </li>
        {% endif %}
    </ul>
{% endif %}

templates/tag_list.html
  <div class="">
    <p class="font-white">タグ一覧</p>
    <div class="categories">
      {% for tags in more_tags %}
      <ul>
        <li><a href="{% url 'article:tag_detail' pk=tags.id %}" class="font-yellow">{{ tags }}：{{ tags.tag_count }}件</a></li>
      </ul>
      {% endfor %}
    </div>
  </div>

templates/tag_list_publick.html
  <div class="">
    <p class="font-white">タグ一覧</p>
    <div class="categories">
      {% for tags in more_tags %}
      <ul>
        <li><a href="{% url 'stweb:tag_detail' pk=tags.id %}" class="font-yellow">{{ tags }}：{{ tags.tag_count_publick }}件</a></li>
      </ul>
      {% endfor %}
    </div>
  </div>