app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from article.urls import router as blog_router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('article/',  include('article.urls')),
    path('',  include('stweb.urls')),
    path('martor/', include('martor.urls')),
    path('api/', include(blog_router.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import ArticleViewSet,TagViewSet, CategoryViewSet


app_name = 'article'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('delete/<int:pk>', views.article_delete, name='article_delete'),
    path('category_detail/<int:pk>', views.category_detail, name='category_detail'),
    path('category/post', views.category_post, name='category_post'),
    path('category/delete/<int:pk>', views.category_delete, name='category_delete'),
    path('tag_detail/<int:pk>', views.tag_detail, name='tag_detail'),
    path('tag/post', views.tag_post, name='tag_post'),
    path('tag/delete/<int:pk>', views.tag_delete, name='tag_delete'),
]

router = routers.DefaultRouter()
router.register(r'articles', ArticleViewSet)
router.register(r'tags', TagViewSet)
router.register(r'categpries', CategoryViewSet)

martor/urls.py
import django
from .views import (markdownfy_view,
                    markdown_imgur_uploader,
                    markdown_search_user)


if django.VERSION >= (2, 0):
    from django.urls import path
    urlpatterns = [
        path('markdownify/', markdownfy_view, name='martor_markdownfy'),
        path('uploader/', markdown_imgur_uploader, name='imgur_uploader'),
        path('search-user/', markdown_search_user, name='search_user_json'),
    ]
else:
    from django.conf.urls import url
    urlpatterns = [
        url(r'^markdownify/$', markdownfy_view, name='martor_markdownfy'),
        url(r'^uploader/$', markdown_imgur_uploader, name='imgur_uploader'),
        url(r'^search-user/$', markdown_search_user, name='search_user_json'),
    ]

article/models.py
from django.db import models
from django.utils import timezone
from user.models import User
from django.utils.html import mark_safe
from markdown import markdown
from simplemde.fields import SimpleMDEField



class Tag(models.Model):
    class Meta:
        db_table = 'tag'
    name = models.CharField('タグ名', max_length=50)
    user = models.ForeignKey(User, verbose_name='ユーザーID', on_delete=models.CASCADE)


    def article_find(self):
        article = Article.objects.filter(tag=self, publick=1)
        return article

    def article_find_publick(self):
        article = Article.objects.filter(tag=self, publick=1)
        return article

    def tag_count(self):
        count = Article.objects.filter(tag=self).count()
        return count

    def tag_count_publick(self):
        count = Article.objects.filter(tag=self, publick=1).count()
        return count

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        db_table = 'category'

    name = models.CharField('カテゴリ名', max_length=50)
    user = models.ForeignKey(User, verbose_name='ユーザーID', on_delete=models.CASCADE)

    def article_count(self):
        count = Article.objects.filter(category_id=self.id).count()
        return count

    def article_count_publick(self):
        count = Article.objects.filter(category_id=self.id, publick=1).count()
        return count

    def __str__(self):
        return self.name

class Article(models.Model):
    class Meta:
        db_table = 'article'

    user = models.ForeignKey(User, verbose_name='ユーザーID', on_delete=models.CASCADE)
    title = models.CharField('タイトル', max_length=255)
    discript = models.TextField('概要', max_length=10000)
    text = models.TextField('本文', max_length=10000)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.SET_NULL, null=True)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='タグ')
    thumnail = models.ImageField(
        'サムネイル', upload_to='image/', blank=True, null=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    publick = models.BooleanField('公開・非公開（チェックすると公開します）', default=True)

    def get_text_as_markdown(self):
        return mark_safe(markdown(self.text, safe_mode='escape'))

    def user_find(self):
        find = User.objects.get(uuid=self.user_id)
        return find

    def category_find(self):
        s = Category.objects.filter(id=self.category_id).get()
        return s

    def tag_find(self):
        s = Tag.objects.filter(article=self)
        return s

    def save_and_rename(self, url, name=None):
        res = requests.get(url)
        if res.status_code != 200:
            return "No Image"
        path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))+"/media/image/"
        if name==None:
            path += url.split("/")[-1]
        else:
            path += name
        with open(path, 'wb') as file:
            file.write(res.content)
        return path

    def __str__(self):
        return self.title

article/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings

from .models import Article, Category, Tag


class PostForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'discript', 'thumnail', 'text', 'category', 'publick',)

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs = {'class': 'form-control'}
        self.fields['discript'].widget.attrs = {'class': 'form-control'}
        self.fields['text'].widget.attrs = {'class': 'form-control'}
        self.fields['category'].widget.attrs = {'class': 'form-control'}
        self.fields['text'].widget.attrs = {'id': 'text-area'}


class TagSelectForm(forms.ModelForm):
    class Meta:
        model = Article.tag.through
        fields = ('tag',)
        widgets = {
            'tag': forms.Select(attrs={
                'class': 'form-control',
            }),
        }

TagInlineFormSet = forms.inlineformset_factory(
    Article, Article.tag.through, form=TagSelectForm, can_delete=False
)


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


class EditForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'discript', 'thumnail', 'text', 'category', 'publick',)

    def __init__(self, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs = {'class': 'form-control'}
        self.fields['discript'].widget.attrs = {'class': 'form-control'}
        self.fields['text'].widget.attrs = {'class': 'form-control'}
        self.fields['category'].widget.attrs = {'class': 'form-control'}
        self.fields['text'].widget.attrs = {'id': 'text-area'}

article/views.py
import logging
import django_filters

from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, reverse
from django.views.generic import View
from django.db.models import F
from django.db.models import Q
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage, InvalidPage
from django.core.paginator import PageNotAnInteger
from pure_pagination.mixins import PaginationMixin
from rest_framework import viewsets, filters


from .forms import PostForm, CategoryForm, EditForm, TagForm, TagSelectForm, TagInlineFormSet
from .models import Category, Article, Tag
from .serializer import ArticleSerializer, CategorySerializer, TagSerializer

from user.models import User



class IndexView(PaginationMixin, LoginRequiredMixin, ListView):
    model = Article
    template_name = 'article/index.html'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        contact_list = Article.objects.filter(user_id=self.request.user.uuid).order_by('-created_at')
        paginator = Paginator(contact_list, 6)
        try:
            page = int(self.request.GET.get('page'))
        except:
            page = 1

        try:
            contact_list = paginator.page(page)
        except(EmptyPage, InvalidPage):
            contact_list = paginator.page(1)

        context['object_list'] = contact_list
        context['articles'] = Article.objects.filter(user_id=self.request.user.uuid).order_by('-created_at')[:5]
        context['count'] = Article.objects.filter(user_id=self.request.user.uuid).count()
        context['more_context'] = Category.objects.filter(user_id=self.request.user.uuid)
        context['more_tags'] = Tag.objects.all()
        return context

index = IndexView.as_view()


class Detail(LoginRequiredMixin, DetailView):
    model = Article
    template_name = 'article/detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['more_context'] = Category.objects.all()
        context['more_tags'] = Tag.objects.all()
        return context

detail = Detail.as_view()


class PostView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = PostForm
    template_name = 'article/post.html'

    def post(self, request, *args, **kwargs):
        form_class = PostForm(request.POST)
        feed_cont = form_class.save(commit=False)
        formset = TagInlineFormSet(self.request.POST, instance=feed_cont)
        if not request.user.is_authenticated:
            messages.info(request, "ログインしてください。。。")
            return redirect('/user/login')
        feed_cont.user_id = request.user.uuid
        feed_cont.save()
        formset.save()
        return redirect('article:detail',pk=(feed_cont.id))

    success_url = "detail"

    def get_context_data(self, **kwargs):
        if 'formset' not in kwargs:
            kwargs['formset'] = TagInlineFormSet(self.request.POST or None)
        return super().get_context_data(**kwargs)

post = PostView.as_view()


class EditView(LoginRequiredMixin, UpdateView):
    model = Article
    form_class = EditForm
    template_name = "article/edit.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        formset = TagInlineFormSet(self.request.POST, instance=self.object)
        if formset.is_valid():
            self.object.save()
            formset.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_context_data(self, **kwargs):
        if 'formset' not in kwargs:
            kwargs['formset'] = TagInlineFormSet(self.request.POST or None, instance=self.object)
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return reverse('article:detail',args=(self.object.id,))

edit = EditView.as_view()


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('article:index')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object.title))
        return result

article_delete = ArticleDeleteView.as_view()


class CategoryDetail(LoginRequiredMixin, DetailView):
    model = Category
    template_name = 'article/category_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article_list'] = Article.objects.filter(category_id=self.object.id).order_by('-id')
        context['count'] = Article.objects.filter(category_id=self.object.id).count()
        context['more_context'] = Category.objects.filter(user_id=self.request.user.uuid)
        context['more_tags'] = Tag.objects.all()

        return context

category_detail = CategoryDetail.as_view()


class CategoryPostView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    categorys = Category.objects.all()
    template_name = 'article/category.post.html'
    success_url = "/article/index/"

    def post(self, request, *args, **kwargs):
        form_class = CategoryForm(request.POST)
        feed_cont = form_class.save(commit=False)
        if not request.user.is_authenticated:
            messages.info(request, "ログインしてください。。。")
            return redirect('/user/login')
        feed_cont.user_id = request.user.uuid
        feed_cont.save()
        return redirect('article:index')

    success_url = "index"


category_post = CategoryPostView.as_view()


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    form_class = CategoryForm

    success_url = reverse_lazy('article:index')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result

category_delete = CategoryDeleteView.as_view()



class TagDetail(LoginRequiredMixin, DetailView):
    model = Tag
    template_name = 'article/tag_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article_list'] = Tag.objects.get(id=self.object.id)
        context['more_context'] = Category.objects.filter(user_id=self.request.user.uuid)
        context['more_tags'] = Tag.objects.all()
        return context

tag_detail = TagDetail.as_view()


class TagPostView(LoginRequiredMixin, CreateView):
    model = Tag
    form_class = TagForm
    tags = Tag.objects.all()
    template_name = 'article/tag.post.html'
    success_url = "/article/index/"

    def post(self, request, *args, **kwargs):
        form_class = TagForm(request.POST)
        feed_cont = form_class.save(commit=False)
        if not request.user.is_authenticated:
            messages.info(request, "ログインしてください。。。")
            return redirect('/user/login')
        feed_cont.user_id = request.user.uuid
        feed_cont.save()
        return redirect('article:index')

    success_url = "index"


tag_post = TagPostView.as_view()


class TagDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    form_class = TagForm

    success_url = reverse_lazy('article:index')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result

tag_delete = TagDeleteView.as_view()


class ArticleViewSet(viewsets.ModelViewSet):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class TagViewSet(viewsets.ModelViewSet):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer

templates/article/article_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p>{{ object.title }} を削除していいですか?</p>
        <form method="post">
          <button class="btn btn-danger">削除する</button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
<a href="{% url 'article:index' %}">記事管理画面</a>
<a href="{% url 'article:post' %}">記事投稿</a>
<a href="{% url 'article:category_post' %}">カテゴリ追加</a>
{% endblock %}

templates/article/category_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p>{{ object }} を削除していいですか?</p>
        <form method="post">
          <button class="btn btn-danger">削除する</button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
<a href="{% url 'article:index' %}">記事管理画面</a>
<a href="{% url 'article:post' %}">記事投稿</a>
<a href="{% url 'article:category_post' %}">カテゴリ追加</a>
{% endblock %}

templates/article/category_detail.html
{% extends "base_detail.html" %}
{% load static %}

{% block pankuzu %}
<div class="container">
<div class="article-detail-pan">
<a href="/">Home</a> > <span>{{ object.name }}</span>
</div>
</div>
{% endblock %}

{% block content %}
<p class="article-count"><span class="font-title">投稿記事:{{ count }}件</span></p>
<p class="text-center index_title">＜<span class="font-bold">{{ object.name }}</span>＞の記事一覧</p>
<div class="row">
  {% for field in article_list %}
  <div class="col-lg-4 col-sm-6">
  <div class="article">
    <div class="article-header">
      <span class="font-small">投稿日:{{field.created_at|date:"Y年n月j日"}}　
        <br />カテゴリ：<a href="{% url 'article:category_detail' pk=field.category_id %}">{{ field.category_find }}</a>
        　<br />タグ：{% for tags in field.tag_find %}
                <a href="{% url 'article:tag_detail' pk=tags.id %}">{{ tags.name }}</a>
              {% endfor %}
    </span>
    </div>
    <a href="{% url 'article:detail' pk=field.id %}" class="article-text">
    <h2 class="t-bg-darkgray-right">{{ field.title }}</h2>
    {% if field.thumnail %}
    <div class="article-thumnail">
      <img class="img-responsive" src="/media/{{ field.thumnail }}">
    </div>
    {% else %}
    {% endif %}
    <div class="t-bg-darkgray-right article-discript">
      <span class="">{{ field.discript }}</span>
    </div>
    <div class="article-see">>> Read more</div>
    </a>
</div>
</div>
{% endfor %}

</div>
  <div class="btn-field">
    <a href="{% url 'article:category_delete' pk=object.id %}">削除</a>
    <a href="{% url 'article:index' %}">記事管理画面</a>
    <a href="{% url 'article:post' %}">記事投稿</a>
    <a href="{% url 'article:category_post' %}">カテゴリ追加</a>
  </div>
{% endblock %}

templates/article/detail.html
{% extends "base.html" %}
{% load static %}

{% block pankuzu %}
<div class="container">
<div class="article-detail-pan">
<a href="/">Home</a> > <a href="{% url 'article:category_detail' pk=object.category_id %}">{{ object.category_find }}</a> > <span>{{ object.title }}</span>
</div>
</div>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-9">
    <div class="article-detail-wrap">
      <div class="article-deatil-link">
        {% if object.updated_at == object.created_at %}
        <span class="font-small">投稿日:{{object.created_at|date:"Y年n月j日"}}</span>
        {% else %}
        <span class="font-small">投稿日:{{object.created_at|date:"Y年n月j日"}}</span>
        　<span class="font-small">追記日：{{ object.updated_at }}</span>
        {% endif %}
        　<br /><span class="font-small">カテゴリ：<a href="{% url 'article:category_detail' pk=object.category_id %}" class="link-view">{{ object.category_find }}</a>　タグ：
        {% for tags in object.tag_find %}
          <a href="{% url 'article:tag_detail' pk=tags.id %}" class="link-view">{{ tags.name }}</a>
        {% endfor %}
      </span>
      </div>
        <div class="article-detail-title">{{ object.title }}</div>
        <div class="article-detail-discript">{{ object.discript }}</div>
        {% if object.thumnail %}
        <img class="img-responsive" src="/media/{{ object.thumnail }}">
        {% else %}
        {% endif %}
        <div id="a"></div>
        <div id="mk-text" class="article-detail-text">{{ object.get_text_as_markdown }}</div>
    </div>
  </div>
  <div class="col-sm-3 text-center">
  {% include 'category_list.html' %}
  {% include 'tag_list.html' %}
</div>
<div class="btn-field">
  <a href="{% url 'article:edit' pk=object.id %}" class="btn btn-secondary">記事編集</a>
  <a href="{% url 'article:article_delete' pk=object.id %}" class="btn btn-warning">削除</a>
  <a href="{% url 'article:index' %}" class="btn btn-info">記事管理画面</a>
  <a href="{% url 'article:post' %}" class="btn btn-primary">記事投稿</a>
  <a href="{% url 'article:category_post' %}" class="btn btn-success">カテゴリ追加</a>
</div>
</div>
{% endblock %}
{% block extra_script %}
<script>
document.getElementById("mk-text").innerHTML = marked(document.getElementById("mk-text").innerHTML);
</script>
<script src="https://cdn.rawgit.com/chjj/marked/master/marked.min.js"></script>
{% endblock %}

templates/article/edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h4 class="text-center">記事編集</h4>
<form action="" method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {{ formset.management_form }}
        {% if form.non_field_errors %}
        <div class="alert alert-warning message">
            <div class="header">エラー</div>
            <ul class="list">
                {% for non_field_error in form.non_field_errors %}
                <li>{{ non_field_error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% for field in form %}
          <div class="form-group">
            <ul>
              <li>{{ field.label }}</li>
              <li>{{ field }}</li>
            </ul>
          </div>
            {% if field.errors %}
          <p class="red message">{{ field.errors.0 }}</p>
          {% endif %}
        {% endfor %}
        {% for tags in formset %}
        {{ tags }}
        {% endfor %}
        <input type="hidden" name="user_id" value="{{ user.uuid }}">
      <input type="submit" value="記事編集" class="btn btn-secondary">
</form>
<div class="btn-field">
<a href="{% url 'article:category_post' %}" class="btn btn-primary">カテゴリ登録</a>
<a href="{% url 'article:index' %}" class="btn btn-primary">記事管理画面</a>
</div>
{% endblock %}

{% block extra_script %}
<script>
var simplemde = new SimpleMDE({
  element: document.getElementById("text-area"),
  autofocus: true,
  forceSync: true,
  placeholder: "本文",
});
</script>
{% endblock %}

templates/article/index.html
{% extends "base_index.html" %}

{% block pankuzu %}
<div class="container">
<div class="article-detail-pan">
<span>Home</span>
</div>
</div>
{% endblock %}

{% load static %}
{% block content %}
<div class="page-top">
  <h4 class="text-center mb20" style="color:#fff;">{{ user.username }}：記事管理画面</h4>
</div>
<p class="article-count"><span class="font-title">投稿記事:{{ count }}件</span></p>
<div class="row">
  {% for field in object_list %}
  <div class="col-lg-4 col-sm-6">
    <div class="article">
        <div class="article-header">
          <span class="font-small">{{field.created_at|date:"Y年n月j日"}}<br />
            カテゴリ：<a href="{% url 'article:category_detail' pk=field.category_id %}">{{ field.category_find }}</a>
            　<br />タグ：{% for tags in field.tag_find %}
                <a href="{% url 'article:tag_detail' pk=tags.id %}">{{ tags.name }}</a>
                  {% endfor %}
        </span>
        </div>
        <a href="{% url 'article:detail' pk=field.id %}" class="article-text">
        <h2 class="t-bg-darkgray-right">{{ field.title }}</h2>
        {% if field.thumnail %}
        <div class="article-thumnail">
          <img class="img-responsive" src="/media/{{ field.thumnail }}">
        </div>
        {% else %}
        {% endif %}
        <div class="article-mr">
        <div class="t-bg-darkgray-right article-discript">
          <span class="">{{ field.discript }}</span>
        </div>
        <div class="article-see">>> Read more</div>
        </div>
        </a>
    </div>
  </div>
  {% endfor %}
  {% include 'pagenation.html' %}
</div>

<div class="btn-field">
  <a href="{% url 'article:post' %}" class="btn btn-primary">記事投稿</a>
  <a href="{% url 'article:category_post' %}" class="btn btn-success">カテゴリ追加</a>
  <a href="{% url 'article:tag_post' %}" class="btn btn-success">タグ追加</a>
</div>
{% endblock %}

templates/article/post.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h4 class="text-center">記事投稿</h4>
<form action="" method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
{{ formset.management_form }}
        {% if form.non_field_errors %}
        <div class="alert alert-warning message">
            <div class="header">エラー</div>
            <ul class="list">
                {% for non_field_error in form.non_field_errors %}
                <li>{{ non_field_error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <div class="form-group">
        {% for field in form %}
            <ul>
              <li>{{ field.label }}</li>
              <li>{{ field }}</li>
            </ul>
            {% if field.errors %}
          <p class="red message">{{ field.errors.0 }}</p>
          {% endif %}
        {% endfor %}
        {% for tags in formset %}
        {{ tags }}
        {% endfor %}
      </div>

        <input type="hidden" name="user_id" value="{{ user.uuid }}">
      <input type="submit" value="記事投稿" class="btn btn-info">
</form>
<div class="btn-field">
<a href="{% url 'article:category_post' %}" class="btn btn-primary">カテゴリ登録</a>
<a href="{% url 'article:index' %}" class="btn btn-primary">記事管理画面</a>
</div>
{% endblock %}

{% block extra_script %}
<script>
var simplemde = new SimpleMDE({
  element: document.getElementById("text-area"),
  autofocus: true,
  forceSync: true,
  placeholder: "本文",
});
</script>
{% endblock %}

templates/article/tag_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p>{{ object }} を削除していいですか?</p>
        <form method="post">
          <button class="btn btn-danger">削除する</button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
<a href="{% url 'article:index' %}">記事管理画面</a>
<a href="{% url 'article:post' %}">記事投稿</a>
<a href="{% url 'article:category_post' %}">カテゴリ追加</a>
{% endblock %}

templates/article/tag_detail.html
{% extends "base_detail.html" %}
{% load static %}

{% block pankuzu %}
<div class="container">
  <div class="article-detail-pan">
    <a href="/">Home</a> > <span>{{ object.name }}</span>
  </div>
</div>
{% endblock %}

{% block content %}
<p class="article-count"><span class="font-title">投稿記事:{{ object.tag_count }}件</span></p>
<p class="text-center index_title">＜<span class="font-bold">{{ object }}</span>＞の記事一覧</p>
<div class="row">
  {% for field in article_list.article_find %}
  <div class="col-lg-4 col-sm-6">
    <div class="article">
      <div class="article-header">
        <span class="font-small">投稿日:{{field.created_at|date:"Y年n月j日"}}　
        <br />カテゴリ：<a href="{% url 'article:category_detail' pk=field.category_id %}" class="link-view">{{ field.category_find }}</a>
      　<br />タグ：{% for tags in field.tag_find %}
          <a href="{% url 'article:tag_detail' pk=tags.id %}" class="link-view">{{ tags.name }}</a>
        {% endfor %}
        </span>
      </div>
      <a href="{% url 'article:detail' pk=field.id %}" class="article-text">
        <h2 class="t-bg-darkgray-right">{{ field.title }}</h2>
        {% if field.thumnail %}
          <div class="article-thumnail">
            <img class="img-responsive" src="/media/{{ field.thumnail }}">
          </div>
        {% else %}
        {% endif %}
        <div class="t-bg-darkgray-right article-discript">
          <span class="">{{ field.discript }}</span>
        </div>
        <div class="article-see">>> Read more</div>
      </a>
    </div>
  </div>
  {% endfor %}
</div>
  <div class="btn-field">
    <a href="{% url 'article:tag_delete' pk=object.id %}">削除</a>
    <a href="{% url 'article:index' %}">記事管理画面</a>
    <a href="{% url 'article:post' %}">記事投稿</a>
    <a href="{% url 'article:category_post' %}">カテゴリ追加</a>
  </div>
{% endblock %}