app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from article.urls import router as blog_router


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('article/',  include('article.urls')),
    path('',  include('stweb.urls')),
    path('martor/', include('martor.urls')),
    path('api/', include(blog_router.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .views import ArticleViewSet,TagViewSet, CategoryViewSet


app_name = 'article'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('delete/<int:pk>', views.article_delete, name='article_delete'),
    path('category_detail/<int:pk>', views.category_detail, name='category_detail'),
    path('category/post', views.category_post, name='category_post'),
    path('category/delete/<int:pk>', views.category_delete, name='category_delete'),
    path('tag_detail/<int:pk>', views.tag_detail, name='tag_detail'),
    path('tag/post', views.tag_post, name='tag_post'),
    path('tag/delete/<int:pk>', views.tag_delete, name='tag_delete'),
]

router = routers.DefaultRouter()
router.register(r'articles', ArticleViewSet)
router.register(r'tags', TagViewSet)
router.register(r'categpries', CategoryViewSet)

martor/urls.py
import django
from .views import (markdownfy_view,
                    markdown_imgur_uploader,
                    markdown_search_user)


if django.VERSION >= (2, 0):
    from django.urls import path
    urlpatterns = [
        path('markdownify/', markdownfy_view, name='martor_markdownfy'),
        path('uploader/', markdown_imgur_uploader, name='imgur_uploader'),
        path('search-user/', markdown_search_user, name='search_user_json'),
    ]
else:
    from django.conf.urls import url
    urlpatterns = [
        url(r'^markdownify/$', markdownfy_view, name='martor_markdownfy'),
        url(r'^uploader/$', markdown_imgur_uploader, name='imgur_uploader'),
        url(r'^search-user/$', markdown_search_user, name='search_user_json'),
    ]

stweb/urls.py
from django.urls import path

from . import views

app_name = 'stweb'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('category_detail/<int:pk>', views.category_detail, name='category_detail'),
    path('tag_detail/<int:pk>', views.tag_detail, name='tag_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<uuid:uuid>/', views.profile, name='profile'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail

import uuid as uuid_lib



class User(AbstractBaseUser, PermissionsMixin):
    uuid = models.UUIDField(default=uuid_lib.uuid4,
                            primary_key=True, editable=False)
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=20,
        unique=True,
        help_text=_('Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    full_name = models.CharField(_('氏名'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), blank=False)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.username

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.forms import UserCreationForm

from .models import User


class RegisterForm(forms.ModelForm):
    """ユーザー登録画面用のフォーム"""

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'ユーザー名'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'パスワード'}),
        }

    password2 = forms.CharField(
        label='確認用パスワード',
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': '確認用パスワード'}),
    )


    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['email'].widget.attrs = {'placeholder': 'メールアドレス'}
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"



    def clean_username(self):
        value = self.cleaned_data['username']
        if len(value) < 2:
            raise forms.ValidationError(
                '%(min_length)s文字以上で入力してください', params={'min_length': 2})
        return value

    def clean_email(self):
        value = self.cleaned_data['email']
        if len(value) < 2:
            raise forms.ValidationError(
                '%(min_length)s文字以上で入力してください', params={'min_length': 2})
        return value

    def clean_password(self):
        value = self.cleaned_data['password']
        return value

    def clean(self):
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError("パスワードと確認用パスワードが合致しません")
        super(RegisterForm, self).clean()


class LoginForm(forms.Form):
    """ログイン画面用のフォーム"""

    username = UsernameField(
        label='ユーザー名',
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'ユーザー名', 'autofocus': True}),
    )

    password = forms.CharField(
        label='パスワード',
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'パスワード'}, render_value=True),
    )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user_cache = None
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"


    def clean_password(self):
        value = self.cleaned_data['password']
        return value

    def clean_username(self):
        value = self.cleaned_data['username']
        if len(value) < 2:
            raise forms.ValidationError(
                '%(min_length)s文字以上で入力してください', params={'min_length': 2})
        return value

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = get_user_model().objects.get(username=username)
        except ObjectDoesNotExist:
            raise forms.ValidationError("正しいユーザー名を入力してください")
        if not user.check_password(password):
            raise forms.ValidationError("正しいユーザー名とパスワードを入力してください")
        self.user_cache = user

    def get_user(self):
        return self.user_cache


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email',)

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs = {'placeholder': 'ユーザー名'}
        self.fields['email'].required = True
        self.fields['email'].widget.attrs = {'placeholder': 'メールアドレス'}
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

    def clean_username(self):
        value = self.cleaned_data['username']
        if len(value) < 2:
            raise forms.ValidationError(
                '%(min_length)s文字以上で入力してください', params={'min_length': 2})
        return value

    def clean_email(self):
        value = self.cleaned_data['email']
        return value

user/views.py
import logging

from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views import View
from django.views.generic import TemplateView
from django.contrib import messages
import uuid as uuid_lib

from .forms import  RegisterForm, ProfileForm, LoginForm

from .models import User
from article.models import Article



logger = logging.getLogger(__name__)


class IndexView(TemplateView):
    template_name = 'user/index.html'
    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            context = super().get_context_data(**kwargs)
            context['more_context'] = Article.objects.all().filter(user_id=self.request.user.uuid)
            number = Article.objects.all().filter(user_id=self.request.user.uuid)
            context['count'] = number.count()
            return context

index = IndexView.as_view()


class RegisterView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'form': RegisterForm(),
        }
        return render(request, 'user/register.html', context)

    def post(self, request, *args, **kwargs):
        logger.info("You're in post!!!")

        form = RegisterForm(request.POST)
        # エラーがある際
        if not form.is_valid():
            return render(request, 'user/register.html', {'form': form})

        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()

        auth_login(request, user)

        return redirect('/user/index/')


register = RegisterView.as_view()


class LoginView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(request, "ログインしています。")
            return redirect(reverse('user:index'))

        context = {
            'form': LoginForm(),
        }
        return render(request, 'user/login.html', context)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        forms = LoginForm()
        if not form.is_valid():
            messages.info(request, "正しい値を入力してください。")
            return render(request, 'user/login.html', {'form': forms})

        user = form.get_user()

        auth_login(request, user)

        messages.info(request, "ログインしました。")

        return redirect(reverse('user:index'))


login = LoginView.as_view()


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            auth_logout(request)
            messages.info(request, "ログアウトしました。")
            return redirect('/user/login')
        if not request.user.is_authenticated:
            messages.info(request, "ログインしてください。。")
            return redirect('/user/login')

logout = LogoutView.as_view()


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = ProfileForm(request.GET or None, instance=request.user)
        context = {
            'form': form,
        }
        return render(request, 'user/profile.html', context)

    def post(self, request, *args, **kwargs):
        logger.info("You're in post!!!")
        form = ProfileForm(request.POST, instance=request.user)
        uuid4 = request.user.uuid
        if not form.is_valid():
            return render(request, 'user/profile.html', {'form': form})

        form.save()

        messages.info(request, "プロフィールを更新しました。")
        return redirect('user:profile', uuid=request.user.uuid)


profile = ProfileView.as_view()

templates/user/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<h2 class="text-center">{{ user.username }}さん</h2>
<div class="text-center pd50">
<a href="{% url 'article:index' %}" class="btn btn-outline-info pd50">記事管理画面はこちらです。</a>
</div>
{% else %}
<p><a href="{% url 'user:login' %}">ログイン</a>してくだしあ。<a href="{% url 'user:login' %}">ログイン</a>をすると、ブログ機能が使えるようになりますよ。</p>
<p>ユーザー登録がおすみでない方は新規ユーザー登録は<a href="{% url 'user:register' %}">こちら</a></p>
{% endif %}
{% endblock %}

templates/user/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div class="row">
  <div class="col-8">
    <div class="text-center pd50">
    <a href="{% url 'article:index' %}" class="btn btn-outline-info pd50">記事管理画面はこちらです。</a>
    </div>
  </div>
  <div class="col-4">
    <h4 class="text-center">{{ user.username }}</h4>
    <ul class="text-center pro-list">
      <li class="art-countbg">記事投稿数：{{ count }}</li>
      {% for articles in more_context %}
      {% empty %}
      <li>記事を投稿していません。投稿しましょう。</li>
      {% endfor %}
      <li><a href="{% url 'user:profile' uuid=user.uuid %}" class="btn link-btn">ユーザー情報更新</a></li>
      <li><a href="{% url 'user:logout' %}" class="btn link-btn">ログアウト</a></li>
    </ul>
  </div>
</div>
{% else %}
<p class="not_login"><a href="{% url 'user:login' %}">ログイン</a>してくだしあ。<a href="{% url 'user:login' %}">ログイン</a>をすると、ブログ機能が使えるようになりますよ。</p>
<p>ユーザー登録がおすみでない方は新規ユーザー登録は<a href="{% url 'user:register' %}">こちら</a></p>
{% endif %}
{% endblock %}

templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}ログイン画面{% endblock %}
{% block content %}
<h2 class="text-center font-barance">ログイン画面</h2>
<form action="" method="post">
  <div class="text-center">
    {% if form.non_field_errors %}
      <div>
        <ul class="alert alert-danger">
          {% for non_field_error in form.non_field_errors %}
            <li>{{ non_field_error }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
    {% for field in form %}
      <div class="form-group">
        <ul>
          <li>{{ field.label }}</li>
          <li>{{ field }}</li>
        </ul>
      </div>
      {% if field.errors %}
      <p class="red message">{{ field.errors.0 }}</p>
      {% endif %}
    {% endfor %}
    {% csrf_token %}
    <input type="submit" class="btn btn-info mt10" value="ログイン">　
  </div>
</form>
<div class="btn-field">
  <a href="{% url 'stweb:index' %}" class="btn btn-primary">TOPへ戻る</a>
</div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2 class="text-center font-barance">プロフィール変更</h2>
<form action="" method="post" class="ui form">
  <div class="text-center">
    {# --- 全体エラーメッセージ --- #}
    {% if form.non_field_errors %}
    <div class="ui red message">
      <div class="header">エラー</div>
      <ul class="list">
        {% for non_field_error in form.non_field_errors %}
          <li>{{ non_field_error }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    {% for field in form %}
      <div class="form-group">
        <ul>
        <li>{{ field.label }}</li>
        <li>{{ field }}</li>
      </ul>
      </div>
      {% if field.errors %}
      <p class="red message">{{ field.errors.0 }}</p>
      {% endif %}
    {% endfor %}
    {% csrf_token %}
    <input type="submit" class="btn btn-info mt10" value="登録情報更新">　
  </div>
</form>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}新規ユーザー登録画面{% endblock %}
{% block content %}
<h4 class="text-center">新規登録画面</h4>
<form action="" method="post" class="ui form">
  {% csrf_token %}
    <div class="ui stacked segment">
        {% if form.non_field_errors %}
        <div class="ui red message">
            <div class="header">エラー</div>
            <ul class="list">
                {% for non_field_error in form.non_field_errors %}
                <li>{{ non_field_error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% for field in form %}
          <ul>
            <li>{{ field }}</li>
          </ul>
          {% if field.errors %}
          <p class="red message">{{ field.errors.0 }}</p>
          {% endif %}
        {% endfor %}
        <input type="submit" class="btn btn-info mt10" value="新規登録">　
    </div>
</form>

<div class="ui message">
  <a class="btn link-btn" href="{% url 'user:login' %}">ログイン</a>
</div>
{% endblock %}